#!/bin/bash
cd folderlistmodel
qmake 
make clean
git co *.cpp *.h
patch -p4    < ../folderlistmodel.diff
qmake
make
cp `qmake -query QT_INSTALL_PREFIX`/qml/Qt/labs/folderlistmodel/libqmlfolderlistmodelplugin.so ..
