.PHONY: install.ppx install.lablqml
install.ppx:
	cp -fv ppx/_build/ppxext/ppx_qt.native $(PREFIX)/bin/ppx_qt

install.lablqml:
	$(MAKE) -C lib install 

install: install.ppx install.lablqml

opam.install:
	$(MAKE) install PREFIX=`opam config var prefix` MAN=`opam config var man` 



