
install.mocml:
	cp src/_build/ppxext/ppx_qt.native $(PREFIX)/bin/ppx_qt
	cp doc/man/mocml.1 $(MAN)/man1/mocml.1

install.lablqml:
	$(MAKE) -C lablqml install 

install: install.mocml install.lablqml

opam.install:
	$(MAKE) install PREFIX=`opam config var prefix` MAN=`opam config var man` 


