lib: [
  "_build/install/default/lib/lablqml/META"
  "_build/install/default/lib/lablqml/dune-package"
  "_build/install/default/lib/lablqml/lablqml.a"
  "_build/install/default/lib/lablqml/lablqml.cma"
  "_build/install/default/lib/lablqml/lablqml.cmi"
  "_build/install/default/lib/lablqml/lablqml.cmt"
  "_build/install/default/lib/lablqml/lablqml.cmti"
  "_build/install/default/lib/lablqml/lablqml.cmx"
  "_build/install/default/lib/lablqml/lablqml.cmxa"
  "_build/install/default/lib/lablqml/lablqml.cmxs"
  "_build/install/default/lib/lablqml/lablqml.h"
  "_build/install/default/lib/lablqml/lablqml.ml"
  "_build/install/default/lib/lablqml/lablqml.mli"
  "_build/install/default/lib/lablqml/liblablqml_stubs.a"
  "_build/install/default/lib/lablqml/opam"
]
doc: [
  "_build/install/default/doc/lablqml/README.md"
]
stublibs: [
  "_build/install/default/lib/stublibs/dlllablqml_stubs.so"
]
