#!/usr/bin/env bash

# code for version checking
verlte() {
    [  "$1" = "`echo -e "$1\n$2" | sort | head -n1`" ]
}
verlt() {
    [ "$1" = "$2" ] && return 1 || verlte $1 $2
}
QT_MIN_VERSION="5.0.0"
QT_VERSION=`qmake -query QT_VERSION`
if ! verlte $QT_MIN_VERSION $QT_VERSION ; then
  echo "Minimal Qt version is $QT_MIN_VERSION (your is $QT_VERSION)" 
  exit
fi



echo "Building custom folderlistmodel plugin"
cd folderlistmodel
if [ ! -e Makefile ];
then
  qmake
fi
make
cd ..
DESTDIR=Qt/labs/folderlistmodel
if [ ! -e $DESTDIR ]; then
  mkdir -p $DESTDIR
fi
cp -f folderlistmodel/qmldir $DESTDIR
cp -f folderlistmodel/plugins.qmltypes $DESTDIR
cp -f folderlistmodel/libqmlfolderlistmodelplugin.so* $DESTDIR


